function [net,pos] = init_network(img_sz, pix_sz, layers,type)
arguments
    img_sz 
    pix_sz 
    layers 
    type (1,:) string {mustBeMember(type, ["NGP","SWAN"])} = "SWAN";
end
xx_ccd = linspace(-img_sz(2)/2 * pix_sz,img_sz(2)/2 * pix_sz,img_sz(2));
yy_ccd = linspace(-img_sz(1)/2 * pix_sz,img_sz(1)/2 * pix_sz,img_sz(1));

switch type
    case "SWAN"
        net = network.SWAN("output_dims", 2,...
                           "Output_size", img_sz,...
                           "base_res", 32,...
                           "high_res", round((img_sz(1) + img_sz(2)) / 2),...
                           "layers", layers,...
                           "hash_level", 12,...
                           "feature_dim", 2,...
                           "log2_hashmap_size", 21,...
                           "bounding_box",[min(xx_ccd(:)),min(yy_ccd(:));...
                                           max(xx_ccd(:)),max(yy_ccd(:))]);
    case "NGP"
        net = network.NGP("output_dims", 2,...
                          "base_res", 32,...
                          "high_res", round((img_sz(1) + img_sz(2)) / 2),...
                          "layers", layers,...
                          "hash_level", 8,...
                          "feature_dim", 4,...
                          "log2_hashmap_size", 21,...
                          "bounding_box",[min(xx_ccd(:)),min(yy_ccd(:));...
                                   max(xx_ccd(:)),max(yy_ccd(:))]);
    otherwise
        error("type must be 'SWAN' or 'NGP'");
end

[xx,yy] = meshgrid(xx_ccd, yy_ccd);

sample_coor = gpuArray(single([xx(:),yy(:)]));
pos = dlarray(sample_coor,"BC");

end