function [net,pos] = init_network(img_sz, pix_sz, layers)
xx_ccd = linspace(-img_sz(2)/2 * pix_sz,img_sz(2)/2 * pix_sz,img_sz(2));
yy_ccd = linspace(-img_sz(1)/2 * pix_sz,img_sz(1)/2 * pix_sz,img_sz(1));

net = network.NGP("output_dims", 4,...
                         "base_res", 16,...
                         "high_res", round((img_sz(1) + img_sz(2)) / 2),...
                         "layers", layers,...
                         "hash_level", 8,...
                         "feature_dim", 4,...
                         "log2_hashmap_size", 21,...
                         "bounding_box",[min(xx_ccd(:)),min(yy_ccd(:));...
                                         max(xx_ccd(:)),max(yy_ccd(:))]);


[xx,yy] = meshgrid(xx_ccd, yy_ccd);

sample_coor = gpuArray(single([xx(:),yy(:)]));
pos = dlarray(sample_coor,"BC");

end