classdef adCodedPtycho < deep.DifferentiableFunction
    properties 
        mag
    end
    methods
        function foo = adCodedPtycho(mag)
            output_num = 1; % important!!!
            
            foo@deep.DifferentiableFunction(...
                        output_num,...
                        SaveInputsForBackward = true,...
                        SaveOutputsForBackward = true,...
                        NumMemoryValues = 2);

            foo.mag = (int32(mag));

        end
        % forward function
        function [observe,memo1,memo2] = forward(foo,...
                                           wavefront1, ...
                                           wavefront2, ...
                                           H_d2,...
                                           shiftsPos)

            % shift_pox = [pos(:,1)';pos(:,2)'];
            [memo1, ...
             memo2, ...
             observe] = cuPtycho_fft_Fwd(...
                                            wavefront1, ...
                                            wavefront2, ...
                                            H_d2, ...
                                            shiftsPos, ...
                                            foo.mag...
                                        );
        end

        % backward function
        function [dldw1,...
                  dldw2,...
                  dldH2,...
                  dldPos] = backward(foo,dl_dout,...
                                     ~,...
                                     wavefront1, ...
                                     wavefront2, ...
                                     H_d2, ...
                                     shiftsPos,...
                                     observe,...
                                     memo1,memo2)

   

            dldH2 = [];
            dldPos = [];
      
            [dldw1,dldw2] = cuPtycho_fft_Bwd(...
                                                dl_dout, ...
                                                observe, ...
                                                memo2, ...
                                                wavefront2, ...
                                                memo1, ...
                                                H_d2, ...
                                                shiftsPos, ...
                                                foo.mag...
                                             );

            % dldw1 = conj(dldw1);
            % dldw2 = conj(dldw2);
        end
    end
end